# MX1: build-time Metal library for the GS Metal backend (cmake -P script).
# Extracts the shader source (the R"METAL(...)METAL" raw string in gs_metal_backend.mm, the single source of
# truth), compiles it with xcrun metal/metallib (math mode safe = the runtime MTLMathModeSafe), and writes a
# C++ unit holding the .metallib bytes and the SHA-256 of the exact source it was built from. The runtime loads
# the metallib only when that hash matches its own kShaderSource; otherwise it compiles the source as before.
# Args: -DSRC=<gs_metal_backend.mm> -DOUT_DIR=<dir> -DOUT_CPP=<file.cpp> [-DMIN_OS=<macOS version>]
cmake_minimum_required(VERSION 3.19)
file(READ "${SRC}" text)
set(open_tag "R\"METAL(")
set(close_tag ")METAL\"")
string(FIND "${text}" "${open_tag}" a)
string(FIND "${text}" "${close_tag}" b)
if(a LESS 0 OR b LESS 0 OR b LESS a)
    message(FATAL_ERROR "gs_metallib: no R\"METAL( ... )METAL\" block in ${SRC}")
endif()
string(LENGTH "${open_tag}" open_len)
math(EXPR start "${a} + ${open_len}")
math(EXPR len "${b} - ${start}")
string(SUBSTRING "${text}" ${start} ${len} shader)
string(SHA256 shader_sha "${shader}")
file(WRITE "${OUT_DIR}/gs_shaders.metal" "${shader}")

set(min_flags)
if(MIN_OS)
    set(min_flags "-mmacosx-version-min=${MIN_OS}")
endif()
execute_process(
    COMMAND xcrun -sdk macosx metal -c -fmetal-math-mode=safe -Wno-unused-variable ${min_flags}
            "${OUT_DIR}/gs_shaders.metal" -o "${OUT_DIR}/gs_shaders.air"
    COMMAND_ERROR_IS_FATAL ANY)
execute_process(
    COMMAND xcrun -sdk macosx metallib "${OUT_DIR}/gs_shaders.air" -o "${OUT_DIR}/gs_shaders.metallib"
    COMMAND_ERROR_IS_FATAL ANY)

file(READ "${OUT_DIR}/gs_shaders.metallib" hex HEX)
string(LENGTH "${hex}" hex_len)
math(EXPR nbytes "${hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
file(WRITE "${OUT_CPP}"
"// generated by gs_metallib.cmake (MX1); do not edit\n#include <cstddef>\n"
"extern \"C\" const unsigned char g_gsmtlMetallib[] = {${bytes}};\n"
"extern \"C\" const size_t g_gsmtlMetallibSize = ${nbytes};\n"
"extern \"C\" const char g_gsmtlMetallibSrcSha256[] = \"${shader_sha}\";\n")
message(STATUS "gs_metallib: ${nbytes} bytes, source sha256 ${shader_sha}")
